### ISSUE TITLE
Defeito precoZeroTest

### ISSUE THREAD

**Issue by ivansenai** [leandrohsilveira/systock#27]
## Descricao do Defeito
O campo de preço embora preenchido com 0,00 nao fica vermelho e o botao salvar é habilitado.

* **Execução ID**: #34
* **Caso de teste ID**: CT-R1-UNI-001
* **Modulo afetado**: precoZeroTest
* **Link acessado**: https://systock.herokuapp.com
* **Usuario/Senha**: gerente/12345678
* **Base de dados**: produção

## Passos

1. Acessar o sistema e autenticar-se;
2. Acessar o cadastro de venda atraves do menu superior "Produto" > "Cadastrar";
3. Preencher o campo preco com valor 0,00;
4. O sistema habilita o botao "Salvar";

**Comment by leandrohsilveira** [comment]
Corrigido

![image](https://cloud.githubusercontent.com/assets/8015037/20032195/614708c0-a36c-11e6-9099-425b59361491.png)
