### ISSUE TITLE
Defeito quantidadeNegativaTest

### ISSUE THREAD

**Issue by ivansenai** [leandrohsilveira/systock#29]
## Descricao do Defeito
O sistema exibe a mensagem incorreta.

* **Execução ID**: #34
* **Caso de teste ID**: CT-R1-UNI-001
* **Modulo afetado**: quantidadeNegativaTest
* **Link acessado**: https://systock.herokuapp.com
* **Usuario/Senha**: gerente / 12345678
* **Base de dados**: produção

## Passos

1. Acessar o sistema e autenticar-se;
2. Acessar o cadastro de venda atraves do menu superior "Produto" > "Cadastrar";
3. O sistema informa uma mensagem diferente do que o caso apresenta;

**Comment by leandrohsilveira** [comment]
![image](https://cloud.githubusercontent.com/assets/8015037/20032181/3ceca516-a36c-11e6-85a8-e87093c2b5d0.png)
