### ISSUE TITLE
Defeito Menu Cliente

### ISSUE THREAD

**Issue by ivansenai** [leandrohsilveira/systock#30]
## Descricao do Defeito
Uma descricao para o defeito

* **Execução ID**: #34
* **Caso de teste ID**: CT-R2-UNI-001
* **Modulo afetado**: Cliente
* **Link acessado**: https://systock.herokuapp.com
* **Usuario/Senha**: gerente / 12345678
* **Base de dados**: produção

## Passos

1. Acessar o sistema e autenticar-se;
2. Acessar o cadastro de cliente atraves do menu superior "Cliente" ;
3. Ao posicionar o mouse sobre o menu "Cliente" o mesmo não apresenta os submenus;

**Comment by leandrohsilveira** [comment]
Corrigir os casos de testes para "Clicar para abrir o menu" ao invés de posicionar o mouse.

**Comment by leandrohsilveira** [comment]
Caso de teste corrigido
